### PR TITLE
Snake tutorial

### PR DESCRIPTION
**Pull request by jrbaxter0**
## Overview
This moves the clock tutorials into their own folder without any modifications, and creates a new folder for the snake game. 

## Verification
See the readme under the snake subdirectory. I'm hoping those instructions are clear enough to get you started. To actually run the game, I like using the `snakesim.launch` file.

Use the RQT GUI that comes up in order to steer the snake. You can use shift + WASD, but I prefer to set the linear velocity up high, then use my mouse to swing the angular velocity left and right rapidly. That is sort of like the "bang-bang" controller Harrison mentioned.

If you die, you can reset by closing and restarting everything, or by calling the reset service. The command to do so is:
`rosservice call /snake/reset "{}"`

## Improvement Ideas
I think my code style isn't very uniform with the PEP8 standard... We could either modify it to meet that standard or create our own.

We could potentially refactor the code into several files. I don't think that is required at the moment because I don't see this as needing to be super modular.

## Dependencies
This breaks the solution branches for the clock tutorials. I think that was a bad implementation to begin with, so we need to fix that anyways.

## Future Work
- create sample solution
- create rqt control panel that implements scoring display and easy reset button along with the steering controller
- track time since reset?

### CODE REVIEW

**Comment by hmccarty** [comment]
Lots of work still needed on tutorial side of things. Following up from our previous discussion, this is supposed an introduction to ROS and initial setup of development environments.

**Comment by jrbaxter0** [comment]
@hmccarty @peytondwilliams @katyayego This is ready for another look. I refactored the code and made it follow closer to the PEP 8 standard. It also follows the ROS format more closely: http://www.artificialhumancompanions.com/structure-python-based-ros-package/

**Comment by jrbaxter0** [comment]
I added in my simple controllers since they were done. For people doing the tutorial, snakesim will mostly be a black box. In the future, it may be used as an example. The snake_tutorial package should be really clean though, because those three nodes are the ones they will need a walk through for. They should be really simple and show good programming and different styles

**Comment by jrbaxter0** [comment]
Docker files are here to get you guys up and running. You need to run `docker-build.sh` to build the docker image. This just passes in args to `docker build`. Then use `docker-run.sh`. Again, this just passes args into `docker run`. Once there, you'll want to:
```bash
cd ~/catkin_ws/
catkin build
source devel/setup.bash
roslaunch snake_tutorial snake.launch
```

To run all that, you need Docker and an X display set up. Getting an X display on WSL2 is kinda tricky, see this: https://stackoverflow.com/questions/61110603/how-to-set-up-working-x11-forwarding-on-wsl2

**Pull request merged**
